DROP TABLE IF EXISTS items CASCADE;

-- ITEMS FOR SALE
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  vendor_id INTEGER REFERENCES vendors(id) ON DELETE CASCADE,
  sold BOOLEAN DEFAULT FALSE,
  date_posted TIMESTAMP DEFAULT now(),
  featured BOOLEAN DEFAULT FALSE,
  category VARCHAR(255) NOT NULL,
  abv INTEGER NOT NULL,
  mliter INTEGER NOT NULL,
  image VARCHAR(255) NOT NULL
);
